import Image from "next/image";import Link from "next/link";import {notFound} from "next/navigation";
import {photos} from "@/lib/data";import {createServerSupabaseClient} from "@/lib/supabase/server";import {getPost} from "@/lib/photos";
import FollowButton from "@/components/FollowButton";import ActionBar from "@/components/ActionBar";import Comments,{CommentRow} from "@/components/Comments";import PostOwnerControls from "@/components/PostOwnerControls";import SaveRecipeButton from "@/components/SaveRecipeButton";import ReportButton from "@/components/ReportButton";
export const dynamic="force-dynamic";
export default async function PhotoPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;let p=photos.find(x=>x.id===id)||null;let live=false,currentId="",liked=false,saved=false,reposted=false,following=false,comments:CommentRow[]=[];
 try{const supabase=await createServerSupabaseClient();const [{data:{user}},post]=await Promise.all([supabase.auth.getUser(),getPost(supabase,id)]);currentId=user?.id||"";if(post){p=post;live=true;const [li,sa,re,fo,co]=await Promise.all([currentId?supabase.from('likes').select('user_id').eq('user_id',currentId).eq('post_id',id).maybeSingle():Promise.resolve({data:null}),currentId?supabase.from('saved_posts').select('user_id').eq('user_id',currentId).eq('post_id',id).maybeSingle():Promise.resolve({data:null}),currentId?supabase.from('reposts').select('user_id').eq('user_id',currentId).eq('post_id',id).maybeSingle():Promise.resolve({data:null}),currentId&&post.ownerId?supabase.from('follows').select('follower_id').eq('follower_id',currentId).eq('following_id',post.ownerId).maybeSingle():Promise.resolve({data:null}),supabase.from('comments').select('id,body,created_at,user_id,profiles!comments_user_id_fkey(username,display_name)').eq('post_id',id).order('created_at')]);liked=!!li.data;saved=!!sa.data;reposted=!!re.data;following=!!fo.data;comments=(co.data||[]) as unknown as CommentRow[];}}
 catch{}if(!p)return notFound();const owner=!!currentId&&currentId===p.ownerId;const displayImages=p.images||[{src:p.src,alt:p.alt}];
 return <main className="shell"><div className="detail"><div className="detailGallery">{displayImages.map((image,index)=><div className="detailImage" key={image.src}><Image src={image.src} alt={image.alt} width={image.width||1500} height={image.height||1000} priority={index===0} style={{width:'auto',height:'auto',maxWidth:'100%',maxHeight:'82vh'}}/></div>)}</div><aside className="panel">
  <div className="userHeader"><Link href={`/${p.user.username}`} className="left"><div className="bigAvatar">{p.user.avatar}</div><div><b>{p.user.name}</b><div className="muted">@{p.user.username}</div></div></Link>{!owner&&p.ownerId&&<FollowButton profileId={p.ownerId} initialFollowing={following}/>}</div>
  {owner&&<PostOwnerControls postId={id} visibility={p.visibility||'public'}/>}<p className="caption">{p.caption}</p>
  <div className="metaGrid"><Meta label="Camera"><Link href={`/cameras/${p.camera.slug}`}>{p.camera.name}</Link></Meta><Meta label="Lens"><Link href={`/lenses/${p.lens.slug}`}>{p.lens.name}</Link></Meta><Meta label="Settings">{p.settings||'Not shared'}</Meta><Meta label="Category"><Link href={`/category/${p.category.toLowerCase().replaceAll(' ','-')}`}>{p.category}</Link></Meta><Meta label="Location">{p.location||'Not shared'}</Meta><Meta label="Visibility">{p.visibility||'public'}</Meta></div>
  {live?<ActionBar postId={id} likes={p.likes} saves={p.saves} initialLiked={liked} initialSaved={saved} initialReposted={reposted}/>:<div className="notice">Community sample — publish your own photo to use social actions.</div>}
  {p.recipe&&<div className="recipe"><div className="eyebrow">Photo recipe</div><h3>{p.recipe.name}</h3>{p.recipe.fields.map(([k,v])=><div className="recipeRow" key={k}><span>{k}</span><b>{v}</b></div>)}{p.recipeId&&<SaveRecipeButton recipeId={p.recipeId}/>}</div>}
  {live&&<><Comments postId={id} items={comments} currentUserId={currentId}/>{!owner&&<ReportButton targetType="post" targetId={id}/>}</>}
 </aside></div></main>;
}
function Meta({label,children}:{label:string;children:React.ReactNode}){return <div><div className="metaLabel">{label}</div><div className="metaValue">{children}</div></div>}
