import Link from "next/link";import {notFound} from "next/navigation";import PhotoGrid from "@/components/PhotoGrid";import FollowButton from "@/components/FollowButton";import MessageButton from "@/components/MessageButton";import ReportButton from "@/components/ReportButton";import BlockButton from "@/components/BlockButton";import {photos} from "@/lib/data";import {createServerSupabaseClient} from "@/lib/supabase/server";import {getPosts} from "@/lib/photos";
export const dynamic="force-dynamic";
type ProfileRow={id:string;username:string;display_name:string;bio:string|null;avatar_url:string|null;location:string|null;website:string|null};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?";
export default async function Profile({params}:{params:Promise<{username:string}>}){
 const {username:raw}=await params;const username=decodeURIComponent(raw).toLowerCase();const seeded=photos.find(p=>p.user.username===username)?.user;let profile:ProfileRow|null=null,currentId="";let items=photos.filter(p=>p.user.username===username);let followers=0,following=0,isFollowing=false,isBlocked=false;
 try{const supabase=await createServerSupabaseClient();const [{data:{user}},{data:p}]=await Promise.all([supabase.auth.getUser(),supabase.from("profiles").select("id,username,display_name,bio,avatar_url,location,website").eq("username",username).maybeSingle()]);currentId=user?.id||"";profile=p as ProfileRow|null;if(profile){const [live,fc,fg,fr,bl]=await Promise.all([getPosts(supabase,{ownerId:profile.id,limit:100}),supabase.from("follows").select("*",{count:"exact",head:true}).eq("following_id",profile.id),supabase.from("follows").select("*",{count:"exact",head:true}).eq("follower_id",profile.id),currentId?supabase.from("follows").select("follower_id").eq("follower_id",currentId).eq("following_id",profile.id).maybeSingle():Promise.resolve({data:null}),currentId?supabase.from("blocks").select("blocker_id").eq("blocker_id",currentId).eq("blocked_id",profile.id).maybeSingle():Promise.resolve({data:null})]);items=live;followers=fc.count||0;following=fg.count||0;isFollowing=!!fr.data;isBlocked=!!bl.data;}}
 catch{}if(!profile&&!seeded)return notFound();const name=profile?.display_name||seeded?.name||username,owner=!!currentId&&currentId===profile?.id;const counts=new Map<string,number>();items.forEach(p=>counts.set(p.camera.name,(counts.get(p.camera.name)||0)+1));const most=[...counts.entries()].sort((a,b)=>b[1]-a[1])[0];
 return <main className="shell"><section className="profileHero">{profile?.avatar_url?<img className="bigAvatar profileAvatarImage" src={profile.avatar_url} alt={`${name}'s avatar`}/>:<div className="bigAvatar">{initials(name)}</div>}<div><h1>{name}</h1><div className="muted">@{username}{profile?.location?` · ${profile.location}`:""}</div>{profile?.bio&&<p className="profileBio">{profile.bio}</p>}{profile?.website&&<a className="profileWebsite" href={profile.website} rel="noreferrer" target="_blank">{profile.website}</a>}<div className="statRow"><span><b>{followers}</b> followers</span><span><b>{following}</b> following</span><span><b>{items.length}</b> posts</span></div><div className="gearSummary">{most&&<span className="pill">Most used: {most[0]} · {most[1]} photos</span>}<Link className="pill" href={`/${username}/gear`}>View gear</Link></div></div><div className="actions">{owner?<Link className="primary" href="/settings">Edit profile</Link>:profile&&<><FollowButton profileId={profile.id} initialFollowing={isFollowing}/><MessageButton profileId={profile.id}/><ReportButton targetType="user" targetId={profile.id}/><BlockButton profileId={profile.id} initial={isBlocked}/></>}</div></section><div className="tabbar"><Link className="active" href={`/${username}`}>Photos</Link><Link href={`/${username}/gear`}>Gear</Link>{owner&&<Link href="/saved">Collections</Link>}</div>{items.length?<PhotoGrid items={items}/>:<div className="empty"><h2>No photos yet</h2><p>{owner?"Upload your first photograph to start building your profile.":"This photographer hasn't published anything yet."}</p>{owner&&<Link className="primary" href="/upload">Upload a photo</Link>}</div>}</main>;
}
